import { Category, TranslationKey } from "./types";

export const CATEGORIES: Category[] = [
  'Starters',
  'Soups',
  'Veg Main Course',
  'Non-Veg Main Course',
  'Chinese',
  'South Indian',
  'Biryani',
  'Snacks',
  'Beverages',
  'Desserts',
  'Special Combos'
];

export const TRANSLATIONS: Record<'en' | 'hi' | 'mr' | 'kok', Record<TranslationKey, string>> = {
  en: {
    welcome_title: "Tulsi Hotel",
    welcome_subtitle: "Experience luxury dining at your fingertips",
    scan_browse_order: "Scan • Browse • Order",
    call_waiter: "Call Waiter",
    categories: "Categories",
    add_to_cart: "Add To Cart",
    view_cart: "View Cart",
    bill_generated_notif: "Your digital bill is ready",
    need_water: "Need Water",
    need_plates: "Need Extra Plates",
    need_tissue: "Need Tissue",
    need_assistance: "Need Assistance",
    need_bill: "Need Bill",
    order_placed_success: "Order Placed Successfully!",
    order_status_received: "Order Received",
    order_status_preparing: "Preparing...",
    order_status_ready: "Hot & Ready!",
    order_status_served: "Served",
    gst: "Taxes & GST (5%)",
    grand_total: "Grand Total",
    confirm_table: "Confirm Table Number",
    customer_name: "Your Name (Optional)",
    mobile_number: "Mobile Number (For Billing/Points)",
    special_instructions: "Special Cooking Instructions",
    place_order: "Place Table Order",
    loyalty_program: "Tulsi Loyalty Points Club",
    feedback: "Customer Feedback & Reviews",
    select_lang: "Select Language"
  },
  hi: {
    welcome_title: "तुलसी होटल",
    welcome_subtitle: "अपनी उंगलियों पर शानदार भोजन का अनुभव करें",
    scan_browse_order: "स्कैन • ब्राउज़ • ऑर्डर",
    call_waiter: "वेटर बुलाएं",
    categories: "श्रेणियाँ",
    add_to_cart: "कार्ट में जोड़ें",
    view_cart: "कार्ट देखें",
    bill_generated_notif: "आपका डिजिटल बिल तैयार है",
    need_water: "पानी चाहिए",
    need_plates: "अतिरिक्त प्लेटें चाहिए",
    need_tissue: "टिशू चाहिए",
    need_assistance: "सहायता चाहिए",
    need_bill: "बिल चाहिए",
    order_placed_success: "ऑर्डर सफलतापूर्वक भेजा गया!",
    order_status_received: "ऑर्डर प्राप्त हुआ",
    order_status_preparing: "तैयार किया जा रहा है...",
    order_status_ready: "गर्मा-गर्म तैयार!",
    order_status_served: "परोसा गया",
    gst: "कर और जीएसटी (5%)",
    grand_total: "कुल योग",
    confirm_table: "टेबल नंबर की पुष्टि करें",
    customer_name: "आपका नाम (वैकल्पिक)",
    mobile_number: "मोबाइल नंबर (बिलिंग/अंकों के लिए)",
    special_instructions: "विशेष खाना पकाने के निर्देश",
    place_order: "टीबल ऑर्डर करें",
    loyalty_program: "तुलसी लॉयल्टी अंक क्लब",
    feedback: "ग्राहक प्रतिक्रिया और समीक्षाएं",
    select_lang: "भाषा का चयन करें"
  },
  mr: {
    welcome_title: "तुळशी हॉटेल",
    welcome_subtitle: "उत्कृष्ट भोजन आपल्या बोटांच्या टोकावर अनुभवा",
    scan_browse_order: "स्कॅन • ब्राउझ • ऑर्डर",
    call_waiter: "वेटरला बोलवा",
    categories: "कॅटेगरी",
    add_to_cart: "कार्ट मध्ये जोडा",
    view_cart: "कार्ट पहा",
    bill_generated_notif: "तुमचे डिजिटल बिल तयार आहे",
    need_water: "पाण्याची गरज आहे",
    need_plates: "अतिरिक्त प्लेट हवी आहे",
    need_tissue: "टिश्यू हवा आहे",
    need_assistance: "मदत हवी आहे",
    need_bill: "बिल हवे आहे",
    order_placed_success: "ऑर्डर यशस्वीरित्या दिली गेली!",
    order_status_received: "ऑर्डर प्राप्त झाली",
    order_status_preparing: "तयार होत आहे...",
    order_status_ready: "गरमा-गरम तयार!",
    order_status_served: "वाढले गेले",
    gst: "कर आणि जीएसटी (5%)",
    grand_total: "एकूण रक्कम",
    confirm_table: "टेबल नंबरची खात्री करा",
    customer_name: "आपले नाव (पर्यायी)",
    mobile_number: "मोबाईल नंबर (बिलिंग/पॉइंट्ससाठी)",
    special_instructions: "विशेष सूचना",
    place_order: "ऑर्डर प्लेस करा",
    loyalty_program: "तुळशी लॉयल्टी पॉईंट्स क्लब",
    feedback: "ग्राहक अभिप्राय व पुनरावलोकने",
    select_lang: "भाषा निवडा"
  },
  kok: {
    welcome_title: "तुळशी हॉटेल",
    welcome_subtitle: "तुमच्या बोटांच्या तोंकार खाशेलें जेवण",
    scan_browse_order: "स्कॅन • पळयात • ऑर्डर करात",
    call_waiter: "वेटर राकरा",
    categories: "श्रेणी",
    add_to_cart: "पोटात घालात",
    view_cart: "पोट पळयात",
    bill_generated_notif: "तुमचे बिल तयार आसा",
    need_water: "उदक जाय",
    need_plates: "प्लेट जाय",
    need_tissue: "टिशू जाय",
    need_assistance: "मदत जाय",
    need_bill: "बिल जाय",
    order_placed_success: "ऑर्डर यशस्वी जाली!",
    order_status_received: "ऑर्डर मेळ्ळी",
    order_status_preparing: "रांदप चालू आसा...",
    order_status_ready: "तांबडे-तय्यार!",
    order_status_served: "वाडलें",
    gst: "टॅक्स आनी जीएसटी (5%)",
    grand_total: "एकूण जेवण खंड",
    confirm_table: "मेज नंबर सिध्द करात",
    customer_name: "तुमचे नांव (इच्छिक)",
    mobile_number: "मोबाईल क्रमांक (गुणां खातीर)",
    special_instructions: "खाशेली रांदप सूचना",
    place_order: "ऑर्डर बुक करात",
    loyalty_program: "तुळशी लॉयल्टी गुणांचो क्लब",
    feedback: "अभिप्राय आनी टिप्पण्यो",
    select_lang: "भास वेचात"
  }
};
